services:
  app-db:
    image: postgres:16
    container_name: crmupload-db
    environment:
      POSTGRES_DB: crmupload-appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5436:5432"
    restart: unless-stopped
    volumes:
      - ./app-db-data:/var/lib/postgresql/data
      - ./db-init/app:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U appuser -d crmupload-appdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ crmuploadnet ]

  crmupload-web:
    image: crmupload-web
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crmupload-web
    depends_on:
      app-db:
        condition: service_healthy
    ports:
      - "8086:8086"
    restart: unless-stopped
    networks: [ crmuploadnet ]
  mailhog:
    image: mailhog/mailhog:latest
    container_name: crmupload-mailhog
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"   # SMTP-Port für EspoCRM
      - "${MAILHOG_HTTP_PORT:-8025}:8025"   # Web UI
    restart: unless-stopped
    networks: [ crmuploadnet ]
networks:
  crmuploadnet:
    external: true