services:
  # --------------------------------------------------------------
  # POSTGRES DATABASE
  # --------------------------------------------------------------
  app-db:
    image: postgres:16
    container_name: crmupload-db
    environment:
      POSTGRES_DB: crmupload-appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "10.10.0.1:5436:5432"                    # optional: Zugriff via WireGuard
    restart: unless-stopped
    volumes:
      - ./app-db-data:/var/lib/postgresql/data
      # - ./db-init/app:/docker-entrypoint-initdb.d:ro   # <- weg: Flyway übernimmt
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U appuser -d crmupload-appdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crmuploadnet

  # --------------------------------------------------------------
  # FLYWAY (one-shot migration job) - SQLs sind IM Image (GHCR)
  # --------------------------------------------------------------
  crmupload-flyway:
    image: ghcr.io/otrturn/crmupload-flyway:prod
    container_name: crmupload-flyway
    command: migrate
    restart: "no"
    depends_on:
      app-db:
        condition: service_healthy
    networks:
      - crmuploadnet
    environment:
      FLYWAY_URL: jdbc:postgresql://crmupload-db:5432/crmupload-appdb
      FLYWAY_USER: appuser
      FLYWAY_PASSWORD: apppass
      FLYWAY_DEFAULT_SCHEMA: app
      FLYWAY_VALIDATE_MIGRATION_NAMING: "true"

  # --------------------------------------------------------------
  # BACKEND WEB API
  # --------------------------------------------------------------
  crmupload-web:
    image: ghcr.io/otrturn/crmupload-web:prod
    container_name: crmupload-web
    depends_on:
      crmupload-flyway:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:8086:8086"   # nur auf localhost!
    restart: unless-stopped
    networks:
      - crmuploadnet
    environment:
      SPRING_PROFILES_ACTIVE: prod

  # --------------------------------------------------------------
  # BACKGROUND WORKER / BATCH PROCESSOR
  # --------------------------------------------------------------
  crmupload-worker-upload:
    image: ghcr.io/otrturn/crmupload-worker-upload:prod
    container_name: crmupload-worker-upload
    depends_on:
      crmupload-flyway:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - crmuploadnet
    volumes:
      - ./tmp:/data/tmp
    environment:
      SPRING_PROFILES_ACTIVE: prod

  crmupload-worker-duplicate-check:
    image: ghcr.io/otrturn/crmupload-worker-duplicate-check:prod
    container_name: crmupload-worker-duplicate-check
    depends_on:
      crmupload-flyway:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - crmuploadnet
    volumes:
      - ./tmp:/data/tmp
    environment:
      SPRING_PROFILES_ACTIVE: prod

  # --------------------------------------------------------------
  # MAILPIT (SMTP debugging)
  # --------------------------------------------------------------
  crmupload-mailpit:
    image: axllent/mailpit:latest
    container_name: crmupload-mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_HTTP_PORT:-8025}:8025"
    restart: unless-stopped
    networks: [ crmuploadnet ]

  # --------------------------------------------------------------
  # BILLING (one-shot batch jobs)
  # --------------------------------------------------------------
  crmupload-billing-generate:
    image: ghcr.io/otrturn/crmupload-billing:prod
    container_name: crmupload-billing-generate
    command: [ "--generateInvoices" ]
    restart: "no"
    depends_on:
      crmupload-flyway:
        condition: service_completed_successfully
    networks:
      - crmuploadnet
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./tmp:/data/tmp

  crmupload-billing-mail:
    image: ghcr.io/otrturn/crmupload-billing:prod
    container_name: crmupload-billing-mail
    command: [ "--mailInvoices" ]
    restart: "no"
    depends_on:
      crmupload-flyway:
        condition: service_completed_successfully
    networks:
      - crmuploadnet
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./tmp:/data/tmp

networks:
  crmuploadnet:
    external: true
